
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2018  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------


default:

prep:
	./prep_txt.sh

clean:
	-rm -f *.tmp
	-rm -f *.dat
	-rm -f a.out

