#!/bin/sh
#
# exports all revisions of all files in RCS dir

files=`ls RCS`

################################################################

RCSAll()
{
  loop="YES"
  file=$1
  i=1
  while :
  do
    i=`expr $i + 1`
    rev="1.$i"

    co -f -l$rev $file 2> tmp.tmp

    actual=`grep '(locked)' tmp.tmp | sed -e 's/revision//' \
		| sed -e 's/(locked)//' | sed -e 's/ *//g'`

    echo "$file $rev $actual"

    if [ $rev != $actual ]; then
      break
    fi

    cvs commit -m 'Checkout of all revisions' $file
  done
}

################################################################

echo "this will do a lot of harm ... aborting for now..."
exit 0

for file in $files
do
  f=`basename $file ,v`
  echo "$file $f"
  RCSAll $f
done
