#!/bin/sh
#
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2018  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------
#
# produces change list of all CVS repositories

# grid not included due to changes in tree

FEMDIR=${FEMDIR:-$HOME/fem}
CDIR=$HOME/c

#-------------------------------------------
crep="$CDIR/mesh $CDIR/post $CDIR/cutils $CDIR/grid"
crep="$CDIR/mesh $CDIR/post $CDIR/cutils"
femrep="$FEMDIR/fem3d $FEMDIR/femplot $FEMDIR/morfo"
#-------------------------------------------

rep="$crep $femrep"
opt=$*

for dir in $rep
do
  echo "-------------------------------------------------------- $dir"
  cd $dir
  cvschange $opt
done
