#!/bin/bash
#
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2018  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------
#
# shows changes of file with respect to last checked in version

cvsadm=CVS
tmpdir=cvsdiff_tmp

#----------------------------------------------------------------

Usage()
{
  echo "Usage: cvsdiff [-h|-help] [-gui] [-header] [-nowhite] [-ifdiff] file(s)"
}

FullUsage()
{
  Usage
  echo "   -h|-help    this help screen"
  echo "   -gui        uses tkdiff to show changes"
  echo "   -header     only checks header for differences"
  echo "   -nowhite    check only no-white space"
  echo "   -ifdiff     show only if differing"
}

ErrorOption()
{
  echo "No such option : $1"
}

#----------------------------------------------------------------

gui="NO"
header="NO"
ifdiff="NO"
options=""

while [ -n "$1" ]
do
   case $1 in
        -gui)           gui="YES";;
        -header)        header="YES";;
        -nowhite)       options="$options -w";;
        -ifdiff)        ifdiff="YES";;
        -h|-help)       FullUsage; exit 0;;
        -*)             ErrorOption $1; exit 1;;
        *)              break;;
   esac
   shift
done

if [ $# -lt 1 ]; then
  Usage
  exit 0
elif [ ! -d $cvsadm ]; then
  echo "No CVS repository found... exiting"
  exit 1
fi

mkdir -p $tmpdir

repo=`cat $cvsadm/Repository`
root=`cat $cvsadm/Root`
base=$root/$repo

echo "looking for file in $base"

#----------------------------------------------- loop on files

for file
do

  co -r -p $base/$file > $tmpdir/$file 2> $tmpdir/rcs_info
  status=$?
  if [ ! -f $file ]; then
    echo "*** Cannot find file $file in current directory"
    exit 1
  elif [ $status -ne 0 ]; then
    echo "*** Cannot find file $file in repository $base"
    exit 1
  fi

  if [ $header = "YES" ]; then
    actfile=$tmpdir/actheader_$file
    repfile=$tmpdir/repheader_$file
    getheader.pl $file > $actfile
    getheader.pl $tmpdir/$file > $repfile
  else
    actfile=$file
    repfile=$tmpdir/$file
  fi

  if [ $ifdiff = "YES" ]; then
    diff -q $options $repfile $actfile > /dev/null
    [ $? -eq 0 ] && continue		#not differing -> skip rest
  fi

  echo "-------------------------------------------------------------"
  ls -la $file
  tail -1 $tmpdir/rcs_info

  if [ $gui = "YES" ]; then
    tkdiff $options $repfile $actfile
  else
    diff $options $repfile $actfile
  fi

  echo "-------------------------------------------------------------"

done

#----------------------------------------------- end of routine

