
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2020  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------


DIR = mwr

default:

clean:
	-rm -f *.dvi *.ps *.aux *.log *.pdf

zip:
	zip $(DIR) *
