
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2018  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------


default: nothing

list: nothing
depend: nothing

clean: nothing
cleanall: clean
	-rm -f mod/*__genmod.f90

fem: nothing
nothing:
	@true

