
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2018  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------


default:

clean:
	-rm -f check.log check_orig.log aux.log copy.log

cleanall: clean

