
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2020  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------


default:

test:
	gfortran test.f
	./a.out

clean:
	-rm -f a.out
	-rm -f *.dat

cleanall: clean

