
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2020  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------


default:

femtime:
	gfortran femtime.f

clean:
	-rm -f *.bak *.tmp *.ps
	-rm -f ggg hhh
	-rm -f a.out
	-rm -f *.o
	-rm -f *.mod

cleanall: clean

