
default:
	@echo "possible targets:"
	@echo "  make_addresses"
	@echo "  send_mail"
	@echo "  dry_run (only to georg)"

make_addresses:
	./make_mail.sh

send_mail:
	mail_shyfem.sh -mail

dry_run:
	mail_shyfem.sh -dry_run

