
default:
	@echo "possible targets:"
	@echo "  addresses"
	@echo "  send_mail"
	@echo "  dry_run (only to georg)"

addresses:
	./make_mail.sh

send_mail:
	mail_shyfem.sh -mail

dry_run:
	mail_shyfem.sh -dry_run

