
SUBDIRS = test1 test2 test3 test4 test5

#---------------------------------------------------

default:

fem:

list:
	pwd; ls

#---------------------------------------------------

clean:
	recursivemake $@ $(SUBDIRS)

cleanall: clean
	recursivemake $@ $(SUBDIRS)

#---------------------------------------------------

