#!/bin/sh
#
#-----------------------------------------------------------------

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
bindir=$FEMDIR/fem3d

#-----------------------------------------------------------------

Usage()
{
  echo "2nc [-h|-help] {-ous|-nos} [-options]"
  echo "   Transforms ous or nos file into netcdf file"
  echo "   One of -ous or -nos must be given"
}

FullUsage()
{
  Usage
  echo "   Options:"
  echo "    -h|-help           this help screen"
  echo "    -ous               convert OUS file to netcdf"
  echo "    -nos               convert NOS file to netcdf"
  echo "    -inter             run interactively"
  echo "    -date date[,time]  set date and time for fem time 0"
  echo "    -dxy dx[,dy]       regular output with grid size dx,dy"
  echo "    -area x0,y0,x1,y1  sets min/max of domain (for regular output)"
  echo "    -period ds,de[,nf] specify start/end date (and freq) for output"
  echo "   Format for date: YYYY[MMDD] and time: hhmmss"
}

ErrorOption()
{
  echo "No such option: $1"
}

#-------------------------------------------------- options

what=""
type="fem"
date=""
area=""
dxy=""
inter="NO"
period=""

while [ -n "$1" ]
do
   case $1 in
        -inter)         inter="YES";;
        -dxy)           dxy=$2; shift;;
        -area)          area=$2; shift;;
        -date)          date=$2; shift;;
        -period)        period=$2; shift;;
        -ous)           what=ous;;
        -nos)           what=nos;;
        -h|-help)       FullUsage; exit 0;;
        -*)             ErrorOption $1; exit 1;;
        *)              break;;
   esac
   shift
done

if [ -z "$what" ]; then
  Usage
  exit 0
fi

if [ $# -ne 0 ]; then
  echo "Extra information on command line: $*"
  Usage
  exit 0
fi

#------------------------------------------------------------

[ -f input.tmp ] && rm -f input.tmp
touch input.tmp

echo ""					>> input.tmp
echo ""					>> input.tmp
echo "$date"				>> input.tmp
echo "$dxy"				>> input.tmp
if [ -n "$dxy" ]; then
  echo "$area"				>> input.tmp
fi
if [ -n "$period" ]; then
  echo "1"				>> input.tmp
  echo "$period"			>> input.tmp
else
  echo "0"				>> input.tmp
fi

#------------------------------------------------------------

prog=$bindir/${what}2nc

echo "running $prog"

if [ $inter = "NO" ]; then
  $prog < input.tmp
else
  $prog
fi

