#!/bin/sh
#
# shell for basinf

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
BINDIR=$FEMDIR/fem3d

recursivemake basinf $BINDIR > /dev/null

if [ $# -gt 0 ]; then
  memory -b $1
else
  #basin=`memory -b`
  #if [ $basin = "UNKNOWN" ]; then
  #  memory -a -b			# this is not working...
  #fi
  :
fi

echo "BINDIR = $BINDIR"
$BINDIR/basinf
