#!/bin/sh

#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2020  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------

file=$1
shift

echo "copying $file to subdirs $*"

for dir
do
  echo "copying $file to subdir $dir"
  if [ -d $dir ]; then
    cp $file $dir
  else
    echo "no such directory $dir ... skipping"
  fi
done
