#!/bin/bash
#
# fembat : runs FEM model
#
####################################################

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}

#---------------------------------------------------
# check command line options
#---------------------------------------------------

#if [ $# -ne 3 ]; then
#	echo "Usage : $0   tmpfile   HP-routine   STR-file"
#	echo "$#: $*"
#	exit 1
#fi

. $HOME/.bash_profile		# for curonian

tmpfile=$1
shift
strfile="${@: -1}"
command=$*

for arg
do
  [ $arg = $strfile ] && break
  program="$program $arg"
done

#echo "Command line: $command"
#echo "tmpfile: $tmpfile"
#echo "program: $program"
#echo "strfile: $strfile"

#---------------------------------------------------
# set parameters
#---------------------------------------------------

timecommand="time"
#timecommand="ggutime"
#timecommand=""
datecommand="date"
infodir=$HOME/tmp/hp/hpinfo
host=`hostname`
actdir=`pwd`

#---------------------------------------------------
# test time command
#---------------------------------------------------

$timecommand ls > /dev/null 2>&1
status=$?
[ $status -ne 0 ] && timecommand=""
#echo "status of time command: $status $timecommand"

#---------------------------------------------------
# set some variables
#---------------------------------------------------

mkdir -p $infodir

auxfile=`basename $tmpfile`
infofile=$infodir/$auxfile
echo "creating info file $infofile"
cp -f $tmpfile $infofile

date=`$datecommand`
start=$date

#---------------------------------------------------
# write to terminal
#---------------------------------------------------

echo " "
echo "$date - $host"
echo " "
echo "actual directory     :  $actdir"
echo " "
echo "FEM routine          :  $program"
echo "input parameter file :  $strfile"
echo " "
echo "compiler version     :"
$FEMDIR/femcheck/identify_compiler.sh
echo " "

#strings $program | grep -i "intel fortran" | head -1

#---------------------------------------------------
# some extra stuff
#---------------------------------------------------

ulimit -s unlimited

#---------------------------------------------------
# run program
#---------------------------------------------------

$timecommand $program $strfile

date=`$datecommand`

echo " "
echo "$date - $host"
echo " "
echo "start:  $start"
echo "end:    $date"
echo " "

#---------------------------------------------------
# clean up
#---------------------------------------------------

rm -f $infofile $tmpfile

#---------------------------------------------------
# end of routine
#---------------------------------------------------

