#!/bin/sh

FEMDIR=${FEMDIR:-$HOME/fem}
BINDIR=$FEMDIR/fem3d

dirname=`dirname $0`
actbin=$dirname/../fem3d

echo    "FEMDIR :   $FEMDIR"
echo    "BINDIR :   $dirname"
echo -n "version:   "
head -1 $actbin/VERSION | sed -e 's/  */ /g' | cut -f4 -d" "

