#!/bin/bash
#
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2020  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------
#
# GUI for "git status" to diff and edit files
#
#----------------------------------------------------------------

command dialog > /dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "dialog not available... exiting"
  exit 1
fi

gui="YES"			#use gui for diffing
if [ "$1" = "-nogui" ]; then
  gui="NO"
fi

#files=$( git s|grep modified:|sed -e 's/\s*modified:\s*//'|sed -e 's/#//' )
files=$( git s --short | grep -E '^.M' | sed -E 's/^.M\s*//' )

n=0
for file in $files
do
  n=$(( n+1 ))
  list="$list $n $file"
  #echo $n $file
  array[$n]=$file
done

w=50
h=$(( n+10 ))
buttons="--extra-button --extra-label edit \
		--ok-label diff --cancel-label exit"

choice=0

#------------------------------------------------------------
# diff:0  exit:3  exit:1
#------------------------------------------------------------

while :
do

  default="--default-item $choice"

  choice=$( dialog $buttons $default \
		--menu "Choose file:" \
		$h $w $n $list 3>&2 2>&1 1>&3 )

  status=$?
  clear

  #echo "exit status = $status"
  #echo "choice = $choice"

  if [ $status -eq 1 ]; then
    break
  elif [ $status -eq 0 ]; then
    file=${array[$choice]}
    echo "diffing $file"
    if [ $gui = "YES" ]; then
      git-diff $file
    else
      git diff $file | less
    fi
  elif [ $status -eq 3 ]; then
    file=${array[$choice]}
    echo "editing $file"
    vi $file
  fi

done

#------------------------------------------------------------

