#!/bin/sh
#
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2020  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------
#
#---------------------------------------------------

gitdir=$HOME/shyfem/fembin/git_info

if [ $# -eq 1 ]; then
  what=$1
else
  echo "Usage: git-info what"
  echo "  what can be one of the following topics:"
  files=$( ls $gitdir )
  for file in $files
  do
    name=$( echo $file | sed -e 's/\.txt//' | sed -e 's/git_info_//' )
    echo "    $name"
  done
  exit 0
fi

file=$gitdir/git_info_$what.txt

if [ -f $file ]; then
  #cat $file
  tail -n +10 $file	# skips copyright
else
  echo "no such info file $file for info $what"
fi

