#!/bin/sh
#
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2020  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------
#
# creates tar file given version or commit
#
#--------------------------------------------------

info="NO"
if [ "$1" = "-info"  ]; then
  info="YES"
  shift
fi

if [ $# -ne 1 ]; then
  echo "Usage: git-tar [-info] {version|commit}"
  exit 0
fi

if [ -f ./fembin/git-util.sh ]; then
  . ./fembin/git-util.sh
else
  echo "...not in base dir"
  exit
fi

#--------------------------------------------------

name=shyfem

ParseVersion $1

if [ -z "$vers" ]; then
  ParseCommit $1
fi

if [ -z "$vers" ]; then
  echo "no such version or commit found ... aborting"
  exit 1
fi

#--------------------------------------------------

prefix=$name-$vers
tarfile=$name-$vers.tar.gz

if [ $info = "YES" ]; then
  echo "$prefix $tarfile"
else
  echo "vers: $vers  prefix: $prefix  tag: $tag  tarfile: $tarfile"
  git archive --format=tar --prefix=$prefix/ $tag | gzip > $tarfile
fi

#--------------------------------------------------

