#!/bin/sh
#
# handles commit and writes to COMMIT file
#
#------------------------------------------------------------
femdir=~/fem/
fembin=$femdir/fembin
commit_file=./COMMIT
version_file=./VERSION
#------------------------------------------------------------

Ask()
{
  echo -n "$1 (y/n) : " | cat >&2
  read yesno
  echo "$yesno"
  [ "$yesno" != "y" ] && exit 1
}

GetMessage()
{
  echo -n "Enter short message: " | cat >&2
  read message
}

#------------------------------------------------------------
# cd to base dir and get info
#------------------------------------------------------------

cd $femdir

git status
git diff --cached --stat

Ask "Continue?"

#------------------------------------------------------------
# prepare log message
#------------------------------------------------------------

GetMessage

echo "============================================================" > log.tmp
echo ""					>> log.tmp
date 					>> log.tmp
echo "" 				>> log.tmp
echo "$message" 			>> log.tmp
echo "" 				>> log.tmp
git diff --cached --stat 		>> log.tmp
echo ""					>> log.tmp

vi log.tmp

#------------------------------------------------------------
# start committing - until here nothing has changed
#------------------------------------------------------------

Ask "Do you really want to commit?"

echo "Preparing commit"

cat log.tmp $commit_file > com.tmp
mv -f com.tmp $commit_file
rm -f log.tmp

line=`$fembin/shyfem_version.pl -noextra $version_file`
extra=commit_`date +"%Y-%m-%d"`
echo "$line   $extra"                > ver.tmp
echo ""                             >> ver.tmp
cat $version_file                   >> ver.tmp
mv -f ver.tmp $version_file

git add $commit_file $version_file

git commit -m "$message" --no-verify

#------------------------------------------------------------
# end of routine
#------------------------------------------------------------

