#!/bin/sh
#
# shell for diffing
#
#--------------------------------------------------

#git difftool --tool=tkdiff --no-prompt $*

what=diff
options=""
files=""
file="NO"
prog=""
nowhite="NO"
zip="NO"
#tool=tkdiff
#tool=xxdiff

Help()
{
  echo "Usage: gitdiff [-h|-help] [options] [tag(s)] [file]"
}

FullHelp()
{
  Help

  echo "  gitdiff                  diff stats between actual and last commit"
  echo "  gitdiff tag              diff stats between actual and tag"
  echo "  gitdiff tag1 tag2        diff stats between tag1 and tag2"
  echo "  gitdiff file             difference of file to last commit"
  echo "  gitdiff tag file         difference of file to commit tag"
  echo "  gitdiff tag1 tag2 file   difference of file between commit tag1 tag2"
  echo "  options:"
  echo "    -w                     do not show difference in white space"
  echo "    -name                  only show name of files that differ"
  echo "    -zip                   zip all changed files to changed.zip"
  echo "  tag can also be origin to see diff between fetch and pull"
}

SetDiffTool()
{
  tool=tkdiff
  [ -n "$( which $tool 2>/dev/null)" ] && return
  echo "...no $tool available... looking for alternatives..."

  tool=xxdiff
  [ -n "$( which $tool 2>/dev/null)" ] && return
  echo "...no $tool available... looking for alternatives..."

  echo "...no suitable difftool found... aborting..."
  exit 1
}

HandleFiles()
{
  if [ -f $1 ]; then
    files="$files -- $1"
    what=difftool
    file="YES"
  elif [ $1 = "origin" ]; then
    files="$files $1/$branch"
  else
    files="$files $1"
  fi
}

#-------------------------------------------------

SetDiffTool
echo "difftool used: $tool"

branch=`git branch | grep '*' | sed -e 's/^\* //'`
echo "We are on branch: $branch"

while [ -n "$1" ]
do
   case $1 in
        -h)             FullHelp; exit 0;;
        -help)          FullHelp; exit 0;;
	-w)		nowhite="YES";;
	-name)		options="$options --name-only";;
	-zip)		zip="YES";;
        -tool)          what="difftool";;
        --*)            options="$options $1";;
        *)              HandleFiles $1;;
  esac
  shift
done

if [ -z "$files" ]; then
  Help
fi

if [ $file = "YES" ]; then
  what=difftool
else
  options="$options --stat"
fi

echo "what:$what  options:$options  files: $files"

if [ $file = "YES" ]; then		#we do compare one file, not only tags
  if [ $nowhite = "YES" ]; then
    git $what $options -x "$tool -w" $files
  else
    git $what $options -x "$tool" $files
  fi
elif [ $zip = "YES" ]; then
  zipfiles=$( git $what $options --name-only $files )
  zip changed.zip $zipfiles
  echo "files have been zipped to changed.zip"
else
  git $what $options $files
fi

#-------------------------------------------------

