#!/bin/sh
#
# shell for diffing
#
#--------------------------------------------------

#git difftool --tool=tkdiff --no-prompt $*

what=diff
options=""
files=""
file="NO"
prog=""
nowhite="NO"

Help()
{
  echo "Usage: gitdiff [-h|-help] [options] [tag(s)] [file]"
}

FullHelp()
{
  Help

  echo "  gitdiff                  diff stats between actual and last commit"
  echo "  gitdiff tag              diff stats between actual and tag"
  echo "  gitdiff tag1 tag2        diff stats between tag1 and tag2"
  echo "  gitdiff file             difference of file to last commit"
  echo "  gitdiff tag file         difference of file to commit tag"
  echo "  gitdiff tag1 tag2 file   difference of file between commit tag1 tag2"
  echo "  options:"
  echo "    -w                     do not show difference in white space"
}

HandleFiles()
{
  if [ -f $1 ]; then
    files="$files -- $1"
    what=difftool
    file="YES"
  else
    files="$files $1"
  fi
}

#-------------------------------------------------

branch=`git branch | grep '*' | sed -e 's/^\* //'`

echo "We are on branch: $branch"

while [ -n "$1" ]
do
   case $1 in
        -h)             FullHelp; exit 0;;
        -help)          FullHelp; exit 0;;
	-w)		nowhite="YES";;
        -tool)          what="difftool";;
        --*)            options="$options $1";;
        *)              HandleFiles $1;;
  esac
  shift
done

if [ -z "$files" ]; then
  Help
fi

if [ $file = "YES" ]; then
  what=difftool
else
  options="$options --stat"
fi

echo "what:$what  options:$options  files: $files"

if [ $nowhite = "YES" ]; then
  git $what $options -x "tkdiff -w" $files
else
  git $what $options $files
fi

#-------------------------------------------------

