#!/bin/sh
#
# shows all changes...
#
# works only if in ~/bin/extDiff the regular diff is set (not tkdiff)
# (is now default)
#
#---------------------------------------------------------------------

for name in $(git diff --name-only $1)
do 
  echo "============================================================"
  echo "        $name                                               "
  echo "============================================================"
  git --no-pager diff $1 $name
done

