#!/bin/sh

cat <<EOI

status			check status of changed files
log			all commits
log --pretty=oneline	one line per commit
show <name>		shows commit or tag <name>
diff <file>		shows diff for <file>
diff --cached
diff --stat		summary of all changes
git diff --cached --stat	-> this output is written to COMMIT (gitcommit)
diff HEAD

add <files>		add <files> to next commit
add -u			add all changed and tracked files to next commit
add .			add all changed files to next commit (also untracked)
commit			commit changes that have been added
tag <tag>		tags with <tag>, if no <tag> shows tags

branch <branch>		creates new <branch>, if non given shows branches
checkout <start>	checks out branch <start>
checkout -b <new> <start>	checks out <start> and creates new branch <new>

HEAD			actual commit
HEAD^			parent of actual commit
HEAD^^			grand-parent
HEAD~4			4th grade

commands:

gitcommit		makes commit writing to COMMIT
gitinfo			this help file
gittag			tags actual commit writing to VERSION
gittags			shows commits and corresponding tags
gittar			makes tar file for given version

todo for a new version:

git status
git diff <file>
revision_last		-> output should go into LOG and BUG
git add -u

gitcommit
gittag

EOI

