#!/bin/sh

if [ $# -ne 1 ]; then
  echo "Usage: gittar vers"
  exit 1
fi

name=shyfem

version=$1
first=`echo $version | cut -b 1`

if [ "$first" = "V" ]; then
  vers=`echo $version | sed -e s/^VERS_//`
  tag=VERS_$vers
elif [ "$first" = "v" ]; then
  vers=`echo $version | sed -e s/^v//`
  tag=v$vers
else
  echo "cannot parse version... first: $first"
  exit 1
fi

prefix=$name-$vers/
tarfile=$name-$vers.tar.gz

echo "vers=$vers  tag=$tag  prefix=$prefix  tarfile=$tarfile"

git archive --format=tar --prefix=$prefix $tag | gzip > $tarfile

