#!/usr/bin/perl -s
#
# shows all tags and commits available
#
# -tagsonly
#
#--------------------------------------------------------------

@tags = `git show-ref --tags`;

foreach $line (@tags) {
  chomp $line;
  my ($hash,$tag) = split(/\s+/,$line);
  $tag =~ s|^refs/tags/||;
  $tags{$hash} = $tag;
  #print "$hash  $tag\n";
}

#exit;

$coms = `git log --pretty=oneline`;
@coms = split(/\n+/,$coms);
@lines = ();

foreach $com (@coms) {
  ($hash,@mess) = split(/\s+/,$com);
  $mess = join(" ",@mess);
  $shorthash = substr($hash,0,10);
  $shortmess = substr($mess,0,55);
  $tag = format_tag($tags{$hash});
  if( $tagsonly ) {
    $tag =~ s/^\s+$//;
    push(@lines,$tag) if( $tag );
  } else {
    my $line = "$shorthash $tag $shortmess";
    push(@lines,$line);
  }
  #print "$line\n";
}

foreach my $line (reverse @lines) {
  print "$line\n";
}

#-------------------------------------------------------------

sub format_tag {

  my ($tag,$size) = shift;

  $tag = "      " unless( $tag );

  my $line = sprintf("%12s",$tag);

  return $line;
}

