#!/bin/sh
#
# shell for tagging git modules in a consistent way

#########################################################

FEMDIR=${FEMDIR:-$HOME/shyfem}
export FEMDIR
version_file="VERSION"
commit_file="COMMIT"

#########################################################

ok()
{
  if [ -z "$1" ]; then
    question="Is this ok (y/N) : "
  else
    question=$1
  fi

  echo
  echo -n "$question"
  read answer

  if [ x.$answer = x."y" ]; then
    :
  else
    exit 0
  fi
}

date2num()
{
#  echo $1 | sed 's/\(.*\)-\(.*\)-\(.*\)/\3\2\1/'
  echo $1 | sed 's/\(.*\)-\(.*\)-\(.*\)/\3\2\1/'
}

editfiles()
{
  lastline=`tail -1 $version_file`
  echo
  echo "You can enter other files to edit before tagging."
  echo "This may be used for logging the new version."
  if [ -n "$lastline" ]; then
    echo "Recommended files: $lastline"
  fi
  echo

  while :
  do

    echo -n "Enter file name to edit ( <CR> to end ) : "
    read file

    if [ -n "$file" ]; then
      vi $file
    else
      break
    fi

  done
}

Usage()
{
  echo ""
  echo "Usage: gittag version"
  echo ""
  echo "   (example: gittag 6.1.7  or  gittag 6.1.7a)"
  echo ""
  if [ $# -ne 1 ]; then
    echo "Actual version : "
    echo "   Version : $2"
    echo "   Date    : $3"
    echo "   Tag     : $4"
    echo ""
  fi
}

AddCommitMessage()
{
  message="New version $newvers"

  echo "============================================================" > log.tmp
  echo ""                                 >> log.tmp
  date                                    >> log.tmp
  echo ""                                 >> log.tmp
  echo "$message"                         >> log.tmp
  echo ""                                 >> log.tmp
  git diff --cached --stat                >> log.tmp
  echo ""                                 >> log.tmp

  cat log.tmp $commit_file > com.tmp
  mv -f com.tmp $commit_file
  rm -f log.tmp
}

#########################################################
tmpfile=tmp0.tmp
tmpfile1=tmp1.tmp
tmpfile2=tmp2.tmp
#########################################################

cd $FEMDIR

if [ ! -f $version_file ]; then
  echo "No file $version_file... maybe in wrong directory"
  exit 2
  #echo "Creating file $version_file ..."
  #touch $version_file
else
  firstline=`head -1 $version_file | sed 's/ \{1,\}/ /g'`
fi

if [ $# -ne 1 ]; then
  Usage $firstline
  git tag
  exit 1
else
  newvers=$1
  newvers=`echo $newvers | sed 's/^v//'`
  newvers=`echo $newvers | sed 's/^VERS_//'`
fi

#########################################################

v=`echo $newvers | sed 's/\./_/g'`
newtag=VERS_$v

newdate=`date +"%d-%m-%Y"`

actvers=`echo $firstline | cut -d" " -f2`
actdate=`echo $firstline | cut -d" " -f3`
acttag=`echo $firstline | cut -d" " -f4`

comparedate=`date2num $actdate`

#########################################################

echo
echo "Actual version :"
echo $actvers "     " $actdate
echo
echo "New version :"
echo $newvers "     " $newdate
echo 

git branch
git status

ok

#########################################################

editfiles

#########################################################

echo
echo "Checking revision log ..."
echo 

files=`find . -name "*.[cfFh]"`
revisionlog -after $comparedate $files > $tmpfile
if [ -f $version_file ]; then
  revisionlog_adjust.pl $tmpfile $version_file > $tmpfile2
fi
cat $tmpfile2

ok

#########################################################

exec 4<&1     # save original stdout
exec > $tmpfile1

echo "version  $newvers    $newdate    $newtag"
echo
echo -n "=========================================================="
echo " $newdate - $newvers"
echo
cat $tmpfile2
echo
echo "=========================================================="
echo
cat $version_file

exec 1<&4     # restore original stdout

vi $tmpfile1

#########################################################

echo ""
echo "new version: $newvers"
echo "new tag    : $newtag"

ok "Shall I tag now ? (y/N) : "

AddCommitMessage
cp $tmpfile1 $version_file	#maybe invert these two lines - done

git add -u
git commit -m "New version $newvers" --no-verify
#touch $version_file
git tag $newtag

rm -f $tmpfile $tmpfile1 $tmpfile2

#########################################################

