#!/bin/sh

info="NO"
if [ "$1" = "-info"  ]; then
  info="YES"
  shift
fi

if [ $# -ne 1 ]; then
  echo "Usage: gittar vers"
  exit 1
fi

name=shyfem

version=$1
first=`echo $version | cut -b 1`

if [ "$first" = "V" ]; then
  vers=`echo $version | sed -e s/^VERS_//`
  tag=VERS_$vers
elif [ "$first" = "v" ]; then
  vers=`echo $version | sed -e s/^v//`
  tag=v$vers
else
  #echo "cannot parse version... first: $first"
  #echo "trying to find commit with this name..."
  git show $version > /dev/null 2>&1
  status=$?
  if [ $status -eq 0 ]; then
    #echo "commit found ... using this version"
    date=`git show --pretty=format:"%ci" $version | head -1 | cut -d " " -f 1`
    #echo "commit date: $date"
    vers=${version}_$date
    tag=${version}
  else
    echo "no such commit found ... aborting"
    exit 1
  fi
fi

prefix=$name-$vers
tarfile=$name-$vers.tar.gz

if [ $info = "YES" ]; then
  echo "$prefix"
else
  echo "vers: $vers  tag: $tag  prefix: $prefix  tarfile: $tarfile"
  git archive --format=tar --prefix=$prefix/ $tag | gzip > $tarfile
fi

