#!/bin/sh
#
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2018  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------
#
# makes complete header files

getheaders.sh $* > head.html
h2t.pl head.html > head.txt
rvlog.pl head.txt > revlog.txt

