#!/bin/sh
#
#-----------------------------------------------------------------

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
bindir=$FEMDIR/fem3d

#-----------------------------------------------------------------

Usage()
{
  echo "2nc [-h|-help] [-options] nc-file"
  echo "   Elaborates nc-file"
  echo "  ********** old version - do not use **********"
}

FullUsage()
{
  Usage
  echo "   Options:"
}

ErrorOption()
{
  echo "No such option: $1"
}

#-------------------------------------------------- options

what=""
type="fem"
date=""
area=""
dxy=""
inter="NO"

while [ -n "$1" ]
do
   case $1 in
        -inter)         inter="YES";;
        -reg)           type="reg";;
        -dxy)           dxy=$2; shift;;
        -area)          area=$2; shift;;
        -date)          date=$2; shift;;
        -h|-help)       FullUsage; exit 0;;
        -*)             ErrorOption $1; exit 1;;
        *)              break;;
   esac
   shift
done

if [ $# -eq 0 ]; then
  Usage
  exit 0
fi

#------------------------------------------------------------

prog=~/bigappl/netcdf/taranto/read/nc_elab

ln -fs $1 nc_file.nc

echo "running $prog"

$prog

