#!/bin/sh
#
#-----------------------------------------------------------------

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
bindir=$FEMDIR/fem3d

#-----------------------------------------------------------------

Usage()
{
  echo "nosaver [-h|-help] {-time|-basin|-vert} [options]"
  echo "    -time     averages nos data over time -> 3d fields"
  echo "    -basin    averages nos data over whole basin -> time series"
  echo "    -vert     averages nos data over vertical -> 2d fields"
  echo "    either -time, -basin, -vert must be specified"
  echo "    options:"
  echo "    -freq freq      uses freq records for averaging over time"
  exit 0
}

#-------------------------------------------------- options

if [ $# -eq 0 ]; then
  Usage
elif [ $1 = "-h" -o $1 = "-help" ]; then
  Usage
fi

if [ $1 = "-time" ]; then
  what=time
elif [ $1 = "-basin" ]; then
  what=basin
elif [ $1 = "-vert" ]; then
  what=vert
else
  Usage
fi

shift

freq=0
if [ "$1" = "-freq" ]; then
  freq=$2
fi

tmpfile=aver.tmp

#-------------------------------------------------- prepare input file

if [ $what = "basin" ]; then
  echo ""  > $tmpfile
  echo "" >> $tmpfile
  $bindir/nosaver_basin < $tmpfile
elif [ $what = "vert" ]; then
  echo ""  > $tmpfile
  echo "" >> $tmpfile
  $bindir/nosaver_vert < $tmpfile
elif [ $what = "time" ]; then
  echo ""  > $tmpfile
  echo "$freq" >> $tmpfile
  $bindir/nosaver_time < $tmpfile
else
  echo "nosaver: internal error: $what"
  exit 1
fi

#-------------------------------------------------- run programs
