#!/bin/sh

#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2018  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------

for file
do
  new=`echo $file | sed -e 's/\.\([0-9][0-9]*\)\./-\1./'`
  echo "$file  ->  $new"
  if [ $file != $new ]; then
    mv $file $new
  fi
done

