#!/bin/sh
#
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2020  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------
#
#-----------------------------------------------------------------

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
bindir=$FEMDIR/fem3d

#-----------------------------------------------------------------

Usage()
{
  echo "ousextr [-h|-help] {-nodes|-records|-gis} data"
  echo "    -nodes      extract nodes given in data"
  echo "    -records    extract records given in data"
  echo "    -gis        extract records given in data in gis format"
  echo "    data        file containing node/record numbers (one on each line)"
  echo "    either -nodes, -records, -gis must be specified"
  exit 0
}

#-------------------------------------------------- options

if [ $# -eq 0 ]; then
  Usage
elif [ $1 = "-h" -o $1 = "-help" ]; then
  Usage
fi

if [ $1 = "-nodes" ]; then
  what=nodes
elif [ $1 = "-records" ]; then
  what=records
elif [ $1 = "-gis" ]; then
  what=gis
else
  Usage
fi

shift

if [ $# -eq 0 ]; then
  Usage
fi

datafile=$1
tmpfile=extr.tmp

if [ ! -f $datafile ]; then
  echo "*** datafile $datafile is not existing ... aborting"
  exit 1
fi

#-------------------------------------------------- prepare input file

if [ $what = "nodes" ]; then
  echo ""  > $tmpfile
  echo "" >> $tmpfile
  cat $datafile >> $tmpfile
  echo "0" >> $tmpfile
  $bindir/ousextr_nodes < $tmpfile
elif [ $what = "records" ]; then
  echo ""  > $tmpfile
  cat $datafile >> $tmpfile
  echo "0" >> $tmpfile
  $bindir/ousextr_records < $tmpfile
elif [ $what = "gis" ]; then
  echo ""  > $tmpfile
  echo "" >> $tmpfile
  cat $datafile >> $tmpfile
  echo "0" >> $tmpfile
  $bindir/ousextr_gis < $tmpfile
else
  echo "internal error..."
  exit 1
fi

#-------------------------------------------------- run programs
