#!/usr/bin/perl -pi.bak

#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2018  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------

s/^%%Orientation: Landscape/%%Orientation: Portrait/;
