#!/bin/sh
#
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2020  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------
#
# exports first revision of all files in RCS dir

files=`ls RCS`

for file in $files
do
  f=`basename $file ,v`
  echo "$file $f"
  co -f -l1.1 $f
done
