#!/bin/sh
#
# shell for readext

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
BINDIR=$FEMDIR/fem3d

if [ $# != 1 ]; then
  echo "Usage: rdext simulation"
  exit 1
fi

simul=$1

file=$simul.ext
if [ ! -f $file ]; then
  echo "No such file: $file"
  exit 1
fi

$BINDIR/readext <<EOI
$simul
EOI

if [ $? -ne 0 ]; then
  echo "Error executing readext..."
  exit 1
fi

echo "Creating time-series files..."

fort76.pl fort.76

