#!/bin/sh
#
# shell for flxinf

FEMDIR=${FEMDIR:-$HOME/fem}
BINDIR=$FEMDIR/fem3d

if [ $# != 1 ]; then
  echo "Usage: rdflx simulation"
  exit 1
fi

simul=$1

file=$simul.flx
if [ ! -f $file ]; then
  echo "No such file: $file"
  exit 1
fi

$BINDIR/flxinf > /dev/null <<EOI
$simul
EOI

