#!/bin/sh
#
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2018  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------
#
# shell for volinf

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
BINDIR=$FEMDIR/fem3d

if [ $# != 1 ]; then
  echo "Usage: rdvol simulation"
  exit 1
fi

simul=$1

file=$simul.vol
if [ ! -f $file ]; then
  echo "No such file: $file"
  exit 1
fi

$BINDIR/volinf > /dev/null <<EOI
$simul
EOI

