#!/bin/sh
#
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2018  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------
#
# calles make recursively (to be used from within makefile)
#
# example:
#
# clean:
#	recursivemake $@ $(SUBDIRS)
#
# versions:
#
# 1.0	unknown		original version
# 1.1	10.12.2013	-quiet flag introduced
#------------------------------------------------------------------

make_option=""
quiet="NO"
if [ "$1" = "-quiet" ]; then
  quiet="YES"
  make_option="--no-print-directory"
  shift
fi
  make_option="--no-print-directory"

if [ $# -lt 1 ]; then
  echo "Usage: recursivemake target dirs"
  exit 1
fi

target=$1
shift

home=`pwd`

if [ $quiet = "NO" ]; then
  echo "making target $target in subdirectories..."
  echo "$*"
fi

for dir
do
  [ $quiet = "NO" ] && echo $dir
  if [ -d $dir ]; then
    cd $dir
    make $make_option $target
    cd $home
  else
    echo "*** no such directory: $dir ... skipping"
  fi
done

