#!/bin/sh
#
# runs adjele

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
BINDIR=$FEMDIR/femadj

adjele=$BINDIR/adjele

Usage()
{
  echo "Usage: regularize input.grd [output.grd]"
}

if [ $# -eq 0 ]; then
  Usage
  exit 1
elif [ $# -eq 1 -a $1 = "-h" ]; then
  Usage
  exit 1
elif [ $# -eq 1 ]; then
  input=$1
  output=""
else
  input=$1
  output=$2
fi

input=`basename $input .grd`
if [ -n "$output" ]; then
  output=`basename $output .grd`
fi

echo  "input file: $input"
echo "output file: $output"

[ -f new.grd ] && rm -f new.grd

$adjele < $input.grd

if [ ! -f new.grd ]; then
  echo "*** error executing adjele ... aborting"
  exit 1
fi

if [ -n "$output" ]; then
  mv new.grd $output.grd
else
  output=new
fi

echo "Ouput has been written to $output.grd"

