#!/bin/sh
#
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2018  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------
#
# executes one command on remotes host(s)

#############################################################

if [ $# -lt 2 ]; then
  echo "Usage remoteshell command remotehost(s)"
  exit 1
fi

command=$1
shift

#############################################################

for remotehost
do

  echo "$remotehost"
  rsh $remotehost "$command"

done

#############################################################

