#!/bin/sh
#
# shows revisions after last VERSION change
#
#----------------------------------------------------

version_file="VERSION"

date2num()
{
  echo $1 | sed 's/\(.*\)-\(.*\)-\(.*\)/\3\2\1/'
}

tmpfile=tmp0.tmp
tmpfile1=tmp1.tmp
tmpfile2=tmp2.tmp

#----------------

firstline=`head -1 $version_file | sed 's/ \{1,\}/ /g'`
actdate=`echo $firstline | cut -d" " -f3`
comparedate=`date2num $actdate`

files=`find . -name "*.[cfFh]"`
#revisionlog -check $files
revisionlog -after $comparedate $files > $tmpfile
revisionlog_adjust.pl $tmpfile $version_file > $tmpfile2

cat $tmpfile2

#----------------

rm -f $tmpfile $tmpfile1 $tmpfile2

#----------------

