#!/bin/sh
#
# processes revision log from fortran files

###############################################################

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
export FEMDIR

###############################################################

usage()
{
  echo 'Usage: revisionlog [-h|-help] [options] files'
}

help()
{
  usage
  echo '  -help           show this help screen'
  echo '  -after date     show only dates after date'
  echo '  -befor date     show only dates befor date'
  echo '  -noname         do not show file name'
  echo '  -sepname        seperate visually file name'
  echo '  -recurse        recurse into subdirs'
  echo '  -check          check header of fortran files'
  echo 'give date in format YYYYMMDD'
}

###############################################################

tmpfile=tmp.tmp
after=0
befor=30000000
recurse=NO

if [ $# -eq 0 ]; then
  usage
  exit 0
fi

options=""

while [ $# -gt 0 ]
do

  case $1 in
        -h|-help) help; exit 0;;
        -after) after=$2; shift 2;;
        -befor) befor=$2; shift 2;;
        -noname) options="$options -noname"; shift;;
        -sepname) options="$options -sepname"; shift;;
        -check) options="$options -check"; shift;;
        -recurse) recurse="YES"; shift;;
        -*) echo "Unknown option: $1"; exit 1;;
        *) break;;
  esac
done

if [ $recurse = "YES" ]; then
  echo "looking in subdirs..."
  files=`find . -name "$*"`
else
  files=$*
fi

#echo "$options -file $file -after $after -befor $befor"

for file in $files
do
  faux=$(echo $file | sed '/\/tmp\//'d)
  #[ -z "$faux" ] && echo "*** skipping $file"
  [ -z "$faux" ] && continue

  getheader.pl $file | revisionlog.pl \
		$options -file $file -after $after -befor $befor
done

###############################################################

