#!/bin/sh
#
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2018  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------
#
# runs scal_intp

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
BINDIR=$FEMDIR/fem3d

progname=scal_intp
prog=$BINDIR/$progname

Usage()
{
  echo "Usage: scal_intp [-h|-help] [-n|-c] [-fact fact] [-file data] basin"
}

FullUsage()
{
  Usage
  echo "  -h|-help     this help screen"
  echo "  -n           give data as \"node value\" in input file (default)"
  echo "  -c           give data as \"x y value\" in input file"
  echo "  -fact fact   factor modulating sphere of influence (default 1)"
  echo "  -file data   name of the file containing the scalar data"
  echo "  basin        name of the basin for which interpolation is done"
  echo ""
  echo "  data is a file that contains single data"
  echo "  points with scalar values. If not specified the file input.dat"
  echo "  is used for the scalar data."
  echo "  basin is a fem-basin file (basin.bas) that has been created"
  echo "  with the command 'vpgrd basin'"
  echo "  The results are written to file scalar.dat and scalar.nos."
}

ErrorOption()
{
  echo "No such option : $1"
}

if [ $# -eq 0 ]; then
  Usage
  exit 1
fi

mode=1
fact=1
data=input.dat

while [ -n "$1" ]
do
   case $1 in
        -n)             mode="1";;
        -c)             mode="2";;
        -file)          data=$2; shift;;
        -fact)          fact=$2; shift;;
        -h|-help)       FullUsage; exit 0;;
        -*)             ErrorOption $1; exit 1;;
        *)              break;;
   esac
   shift
done

if [ $# -eq 0 ]; then
  Usage
  exit 1
else
  basin=$1
fi

dir=`dirname $basin`
basin=`basename $basin .bas`
if [ "$dir" != '.' ]; then
  basin="$dir/$basin"
fi

echo "mode:  $mode"
echo "data:  $data"
echo "fact:  $fact"
echo "basin: $basin"
echo "dir:   $dir"

if [ ! -x $prog ]; then
  pushd $BINDIR
  make scal_intp
  popd
fi
if [ ! -x $prog ]; then
  echo "Cannot find or make $progname."
  exit 1
fi

ln -s $data input.dat

$prog <<EOI
$basin
$mode
$fact
EOI

rm -f input.dat

