#!/usr/bin/perl

# scales column

$col = 1;
$fact = 1;
$const = 0;

&handle_args;

if( $help ) {
  FullUsage();
} elsif( !@ARGV ) {
  Usage();
}

$col--;

while(<>) {

  chomp;
  s/^\s*//;
  $comment = 0;
  $comment = 1 if /^\#/;
  @data = split;
  my $n = @data;
  if( $n > 0 and not $comment ) {
    $data[$col] *= $fact;
    $data[$col] += $const;
    $_ = join(" ",@data);
  }

  print "$_\n";
}

$col++;
print STDERR "Column $col scaled with $fact\n" if $verb;

#--------------------------------------

sub make_fact {

  my $f = shift;
  my $fact;

  my $string = '$fact = ' . "$f;";

  eval $string;

  return $fact;
}

sub handle_args {

  while( $arg = $ARGV[0] ) {

    if( $arg =~ /^-c/ ) {
	$col = $ARGV[1];
	shift @ARGV;
    } elsif( $arg =~ /^-a/ ) {
	$const = &make_fact($ARGV[1]);
	shift @ARGV;
    } elsif( $arg =~ /^-s/ ) {
	$fact = &make_fact($ARGV[1]);
	shift @ARGV;
    } elsif( $arg =~ /^-i/ ) {
	$fact = &make_fact($ARGV[1]);
	$fact = 1. / $fact;
	shift @ARGV;
    } elsif( $arg =~ /^-verb/ ) {
	$verb = 1;
    } elsif( $arg =~ /^-help/ ) {
	$help = 1;
    } elsif( $arg =~ /^-h/ ) {
	$help = 1;
    } elsif( $arg =~ /^-/ ) {
	die "Unknown command line argument: $arg\n";
    } else {
	last;
    }

    shift @ARGV;
  }

}

sub Usage {

  print STDERR "Usage: scalecol [-h|-help] [-options] file\n";
  exit 1;
}

sub FullUsage {

  print STDERR "Usage: scalecol [-h|-help] [-options] file\n";
  print STDERR "  options can be:\n";
  print STDERR "    -h|-help      this help screen\n";
  print STDERR "    -c col        scale column col (default 1)\n";
  print STDERR "    -s factor     use this scaling factor (default 1)\n";
  print STDERR "    -i rfactor    use scaling factor 1/rfactor (default 1)\n";
  print STDERR "    -a const      add this constant (default 0)\n";
  print STDERR "    -verb         be verbose (write info to terminal)\n";
  exit 1;
}

