#!/bin/sh
#
# shell for splitflx

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
BINDIR=$FEMDIR/fem3d

if [ $# != 1 ]; then
  echo "Usage: spltflx simulation"
  exit 1
fi

simul=$1

file=$simul.ext
if [ ! -f $file ]; then
  echo "No such file: $file"
  exit 1
fi

$BINDIR/splitflx <<EOI
$simul
EOI

if [ $? -ne 0 ]; then
  echo "Error executing splitflx..."
  exit 1
fi

