#!/bin/sh
#
# shell for splitext

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
BINDIR=$FEMDIR/fem3d

if [ $# != 1 ]; then
  echo "Usage: spltext simulation"
  exit 1
fi

simul=$1

file=$simul.ext
if [ ! -f $file ]; then
  echo "No such file: $file"
  exit 1
fi

$BINDIR/splitext <<EOI
$simul
EOI

if [ $? -ne 0 ]; then
  echo "Error executing splitext..."
  exit 1
fi

