#!/bin/sh

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
BINDIR=$FEMDIR/fem3d

str=$1
strfile=`basename $str .str`
strfile=$strfile.str

if [ $# -eq 0 ]; then
  echo "Usage: strnodes str-file"
  exit 0
fi
if [ ! -f $strfile ]; then
  echo "No such file: $strfile"
  echo "Usage: strnodes str-file"
  exit 0
fi

getstrnodes.pl $strfile > nodes_s.lst

basin=`strtitle -b $strfile`

#echo "$basin   $strfile"

if [ ! -x $BINDIR/bastreat ]; then
  act=`pwd`
  cd $BINDIR
  make bastreat
  cd $act
fi

$BINDIR/bastreat <<EOI
$basin
4
EOI

