#!/bin/sh
#
# makes symlinks
#
# Usage: symlink [-remove] dir routine(s)
#
#-------------------------------------------------------

remove="NO"
if [ "$1" = "-remove" ]; then
  remove="YES"
  shift
fi

dir=$1
shift

if [ -z "$dir" ]; then
  echo "Usage: symlink [-remove] dir routine(s)"
  exit 0
elif [ -d $dir ]; then
  :
  #echo "symlink directory is $dir"
else
  echo "no such directory: $dir"
  exit 1
fi

actdir=`pwd -P`
cd $dir

for file
do
  #echo "acting on file $file (remove=$remove)"
  if [ $remove = "YES" ]; then
    if [ -f $file -o -L $file ]; then
      echo "removing symlink in $dir: $file"
      rm -f $file
    fi
  else
    if [ ! -f $file ]; then
      echo "making symlink in $dir: $file"
      ln -fs $actdir/$file
    fi
  fi
done

