#!/bin/sh
#
# shell for vp

FEMDIR=${FEMDIR:-$HOME/fem}
BINDIR=$FEMDIR/fem3d

##################################### help function

help()
{
  echo "Usage: vpgrd [-noopt] [-h|-help] basin"
}

##################################### options

GetVp()
{
  if [ -x "vp" ]; then
    vpexe="vp"
  elif [ -x "$BINDIR/vp" ]; then
    vpexe="$BINDIR/vp"
  else
    actual=`pwd`
    cd $BINDIR
    make vp
    cd $actual
    vpexe="$BINDIR/vp"
  fi
}
##################################### options

opt="YES"	#optimization is on

while [ $# -gt 0 ]
do
  case $1 in
        -noopt) opt="NO";;
        -help)  help; exit 1;;
        -h)     help; exit 1;;
        -*)     echo "Unknown option: $1"; exit 1;;
         *)     break;;
  esac
  shift
done

###################################### check file name

if [ -z "$1" ]; then
  help
  exit 1
fi

name=`basename $1 .grd`
file=$name.grd

if [ ! -f $file ]; then
  echo "No such file: $file"
  exit 1
fi

GetVp
#echo "vp: $vpexe"
if [ -z "$vpexe" ]; then
  echo "No executable vp"
  exit 1
fi

##################################### run vp

if [ $opt = "YES" ]; then

$vpexe <<EOI
$name
yes
yes
EOI

else

$vpexe <<EOI
$name
no
EOI

fi

##################################### end

