#!/bin/sh
#
# shell for vp

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
BINDIR=$FEMDIR/fem3d

##################################### help function

Usage()
{
  echo "Usage: vpgrd [-noopt] [-h|-help] basin"
}

##################################### options

opt="YES"	#optimization is on

while [ $# -gt 0 ]
do
  case $1 in
        -noopt) opt="NO";;
        -help)  Usage; exit 1;;
        -h)     Usage; exit 1;;
        -*)     echo "Unknown option: $1"; exit 1;;
         *)     break;;
  esac
  shift
done

###################################### check file name

if [ -z "$1" ]; then
  Usage
  exit 1
fi

vpexe="$BINDIR/vp"
if [ -x "$vpexe" ]; then
  echo "No executable vp"
  exit 1
fi

name=`basename $1 .grd`
file=$name.grd

if [ ! -f $file ]; then
  echo "No such file: $file"
  exit 1
fi

##################################### run vp

if [ $opt = "YES" ]; then

$vpexe <<EOI
$name
yes
yes
EOI

else

$vpexe <<EOI
$name
no
EOI

fi

##################################### end

