#!/bin/sh
#
# shell for vp
#
#----------------------------------------------------------

FEMDIR=${SHYFEMDIR:=$HOME/shyfem}
BINDIR=$FEMDIR/fem3d

##################################### help function

Usage()
{
  echo "Usage: vpgrd [-h|-help] [-options] basin"
}

FullUsage()
{
  Usage
  echo "  options:"
  echo "    -h!-help      this help"
  echo "    -noopt        do not optimize"
  echo "    -quiet        run quietly"
  echo "    -info         do not make bas, only write info on grd"
}

##################################### options

options=""
opt="YES"	# optimization is on
quiet="NO"	# be quiet
info="NO"	# only info
envir="NO"	# info on environment

while [ $# -gt 0 ]
do
  case $1 in
        -noopt) opt="NO", options="$options -noopt";;
	-quiet) quiet="YES";;
	-info) info="YES", options="$options -info";;
	-envir) envir="YES";;
        -help)  FullUsage; exit 0;;
        -h)     FullUsage; exit 0;;
        -*)     echo "Unknown option: $1"; exit 1;;
         *)     break;;
  esac
  shift
done

###################################### check file name

if [ -z "$1" ]; then
  Usage
  exit 1
fi

dir=`dirname $1`
name=`basename $1 .grd`
file=$dir/$name.grd
filen=$dir/$name

if [ ! -f $file ]; then
  echo "No such file: $file"
  exit 1
fi

if [ $envir = "YES" ]; then
  echo "FEMDIR = $FEMDIR"
fi

echo "dimension info on file $file:"
$FEMDIR/fembin/grd_info.pl -dim $file		# write info on file

[ $info = "YES" ] && exit 0

vpexe="$BINDIR/vp"
vpexe="$BINDIR/shypre"
if [ ! -x "$vpexe" ]; then
  echo "No executable shypre in $BINDIR"
  exit 1
fi

##################################### run vp

echo $filen > vpinput.tmp		# name of basin
echo $opt >> vpinput.tmp		# optimization
echo "YES" >> vpinput.tmp		# automatic optimization

echo "options: $options   file: $file"

if [ $quiet = "YES" ]; then
  #$vpexe < vpinput.tmp > vpoutput.tmp
  $vpexe $options $file > vpoutput.tmp
else
  #$vpexe < vpinput.tmp
  $vpexe $options $file
fi



##################################### end

