
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2018  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------


default: nothing

fem: nothing

regress: nothing

status: nothing

list:
	pwd; ls

depend: nothing

clean: nothing

cleanall: nothing

save: nothing

zip: nothing

nothing:
	@true

