
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2020  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------

DIR = fempara

LIBDIR = ../femlib
LIB     = $(LIBDIR)/libparalution.a

#-----------------------------------------------------------

default: nothing

fem: nothing

nothing:
	@true

list:
	@pwd; ls

depend: nothing

clean:
	@rm -f $(LIB)

cleanall: clean

#-----------------------------------------------------------

