
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2018  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------


FEMDIR    = ..
FEMBIN    = $(FEMDIR)/fembin

FEMDIRS   = femfiles mpi stab

#-----------------------------------------------------------------------

default:

fem:

regress:

list:
	pwd; ls

depend:

clean:
	$(FEMBIN)/recursivemake $@ $(FEMDIRS)

cleanall:
	$(FEMBIN)/recursivemake $@ $(FEMDIRS)

save:

zip:

#-----------------------------------------------------------------------

