
FEMDIR    = ..
FEMBIN    = $(FEMDIR)/fembin

FEMDIRS   = femfiles

#-----------------------------------------------------------------------

default:

fem:

regress:

list:
	pwd; ls

depend:

clean:
	$(FEMBIN)/recursivemake $@ $(FEMDIRS)

cleanall:
	$(FEMBIN)/recursivemake $@ $(FEMDIRS)

save:

zip:

#-----------------------------------------------------------------------

