#$Id: Makefile,v 1.6 2005-07-06 14:07:17 kbk Exp $
#
# Makefile to build the the Turbulence library - libturbulence.a
#

include ../Rules.make

DIR     = turbulence

#------------------------------------------------------------

LIBGOTM  = gotm
LIB = $(DIRLIB)/lib$(LIBGOTM).a

#------------------------------------------------------------

DOCSRC	= \
turbulence.F90		\
production.F90          \
alpha_mnb.F90           \
r_ratio.F90             \
tkeeq.F90		\
q2over2eq.F90		\
kbeq.F90		\
lengthscaleeq.F90	\
dissipationeq.F90	\
genericeq.F90	        \
tkealgebraic.F90	\
kbalgebraic.F90	        \
algebraiclength.F90	\
epsbalgebraic.F90	\
variances.F90	        \
ispralength.F90		\
potentialml.F90	        \
cmue_a.F90              \
cmue_b.F90              \
cmue_c.F90              \
cmue_d.F90              \
cmue_ma.F90		\
cmue_sg.F90		\
cmue_rf.F90		\
compute_cpsi3.F90	\
compute_rist.F90	\
internal_wave.F90       \
fk_craig.F90            \
kpp.F90                 \
diff_face.F90		\
tridiagonal.F90		\
gotm_lib_version.F90

MOD   = \
turbulence.o   \
eqstate.o   \
util.o   \
tridiagonal.o	\
kpp.o

OBJ   = \
diff_face.o		\
gotm_lib_version.o	\
production.o            \
alpha_mnb.o             \
r_ratio.o               \
tkeeq.o			\
q2over2eq.o		\
tkealgebraic.o		\
kbeq.o	          	\
kbalgebraic.o		\
dissipationeq.o		\
genericeq.o		\
lengthscaleeq.o		\
algebraiclength.o	\
epsbalgebraic.o  	\
variances.o      	\
ispralength.o		\
potentialml.o		\
cmue_a.o		\
cmue_b.o		\
cmue_c.o		\
cmue_d.o		\
cmue_ma.o		\
cmue_rf.o		\
cmue_sg.o		\
compute_cpsi3.o		\
compute_rist.o		\
fk_craig.o		\
internal_wave.o		\

fem: all libgotm

all: $(MOD) ${OBJ}
#	$(LINKER) $(LFLAGS) $(MOD) ${OBJ} -o $@
	$(MOVE_MODULES_COMMAND)

#$(OBJ): $(MOD)

doc:    $(DOCSRC)
	$(PROTEX) $(DOCSRC) > ../../doc/turbulence.tex 
	touch doc

clanall: clean

clean:
	$(RM) -f ${LIB} *.mod *.o
#	$(RM) -f ${LIB} $(MODDIR)/turbulence.{m,mod} $(MODDIR)/kpp.{m,mod} doc

realclean: clean
	$(RM) -f *.o *~

distclean: realclean

libsym:
	ar rvs $(LIB) $?

libgotm: $(LIB)
$(LIB): $(MOD) $(OBJ)
	ar rvs $(LIB) $?

.SUFFIXES:
.SUFFIXES: .F90

.F90.o:
	$(F77) $(FFOLD) -c $(FFLAGS) $<

%.o: %.F90
	$(F77) $(FFLAGS) -c $< 

diff_face.o: cppdefs.h
gotm_lib_version.o: cppdefs.h
production.o: cppdefs.h
alpha_mnb.o: cppdefs.h
r_ratio.o: cppdefs.h
tkeeq.o: cppdefs.h
q2over2eq.o: cppdefs.h
tkealgebraic.o: cppdefs.h
kbeq.o: cppdefs.h
kbalgebraic.o: cppdefs.h
dissipationeq.o: cppdefs.h
genericeq.o: cppdefs.h
lengthscaleeq.o: cppdefs.h
algebraiclength.o: cppdefs.h
epsbalgebraic.o: cppdefs.h
variances.o: cppdefs.h 
ispralength.o: cppdefs.h
potentialml.o: cppdefs.h
cmue_a.o: cppdefs.h
cmue_b.o: cppdefs.h
cmue_c.o: cppdefs.h
cmue_d.o: cppdefs.h
cmue_ma.o: cppdefs.h
cmue_rf.o: cppdefs.h
cmue_sg.o: cppdefs.h
compute_cpsi3.o: cppdefs.h
compute_rist.o: cppdefs.h
fk_craig.o: cppdefs.h
internal_wave.o: cppdefs.h

#-----------------------------------------------------------------------
# Copyright by the GOTM-team under the GNU Public License - www.gnu.org
#-----------------------------------------------------------------------
