
#--------------------------------------------------------------------------
#
#    Copyright (C) 1985-2020  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#--------------------------------------------------------------------------

default:

clean:
	-rm -f *.bak *.tmp *.ps
	-rm -f ggg hhh
	-rm -f a.out

cleanall: clean

