
#------------------------------------------------------------------------
#
#    Copyright (C) 1985-2020  Georg Umgiesser
#
#    This file is part of SHYFEM.
#
#------------------------------------------------------------------------


default: nothing

fem: nothing

regress: nothing

status: nothing

list:
	pwd; ls

depend: nothing

clean:
	-rm -f lin_*.txt
	-rm -f exp_*.txt
	-rm -f *.ps
	-rm -f *.tmp *.bak

cleanall: clean

save: nothing

zip: nothing

nothing:
	@true

